### PR TITLE
Adding third opendag button

### PR DESCRIPTION
**Pull request by Souf149**
I added the third open dag button on the home screen as requested as the PO [Proof](http://prntscr.com/n626tx)

### CODE REVIEW

**Comment by YASIN078** [comment]
Great code, you have a very good layout.

**Comment by YASIN078** [comment]
Great code, you have a very good layout.

**Review by YASIN078 — APPROVED** [review]
Great code, good that you did not forgot.

**Review by uev52 — DISMISSED** [review]
Remove the text: "Choose one openday" and change it with "Opendays" as the PO said

**Pull request merged**
