### PR TITLE
The info buttons+schedubuttons+ sharing (openday screen and sharing functionality)

### PR DESCRIPTION
**Pull request by uev52**
1) the linking to the other general information screen are made (what was possible) /with working buttons

2) the button that changes the schedule and text on the bottom part of the openday screens are made

3) the sharing button is add to the menu of openday screen and default functionality is set

### CODE REVIEW

**Review by SevvenvanderVlist — COMMENTED** [review]
I don't see what you mean with your first pint that you made of the lining of other general information screens.
The other 2 points seem to be working fine with me. I think some buttons should be removed from the Share button but the basic functionality of it appears to be working fine.

**Review by Souf149 — CHANGES_REQUESTED** [review]
Looks very good and very nice functionality 👍

Only I can't see the bottom of the screen. Maybe make it scrollable?

[screenshot](http://prntscr.com/njyi6i) for reference

**Comment by uev52** [comment]
> Looks very good and very nice functionality 👍
> 
> Only I can't see the bottom of the screen. Maybe make it scrollable?
> 
> [screenshot](http://prntscr.com/njyi6i) for reference

it's clear, i will change it 👍

**Comment by uev52** [comment]
Add a scrollview, the scrollview is working now

**Review by Souf149 — APPROVED** [review]
The problems have been fixed

**Pull request merged**
